Add covid symptom annotator specification
nlpsandbox/nlpsandbox-schemas pull request #195
Opened 2021-04-13 21:08 UTC by tschaffter

Fixes #192

2021-04-13 21:16 UTC, tschaffter commented
@ymnliu Should the annotator be called `covid19-symptom-annotator`? It's more descriptive, but if we expect this annotator to work with other covid-x, we may prefer to keep it's name more generic..

2021-04-20 21:07 UTC, ymnliu commented
Hi @tschaffter would you like to review this PR?

2021-04-20 21:38 UTC, tschaffter commented
@ymnliu I fixed a conflict that was blocking this branch from starting the tests.

2021-04-20 21:42 UTC, tschaffter commented
@ymnliu I cannot review this PR since I created it. Below are my comments:

- I should not have removed the schemas listed in your commit "remove unrelated annotations". These schemas are used by other tools. This repository lists schemas for many tools, not just the COVID annotator.
- The convention in this repo is to use snake case for enumeration (e.g. `nasal_obstruction` instead of `Nasal obstruction`).
- The documentation of the tool in the file `openapi/covid-symptom-annotator/openapi.yaml` must be updated.

2021-04-20 21:47 UTC, tschaffter commented
@ymnliu You can use [git revert](https://www.gitkraken.com/learn/git/problems/revert-git-commit) to revert the commit where you remove the files that must be kept.

2021-04-22 20:16 UTC, ymnliu commented
Hi @tschaffter I was removing the deid scheme files from the branch, which are included from the very beginning of the branch. I assume I should use git rm instead? Anyway, I will fix it based on your review comments.

2021-04-22 20:50 UTC, tschaffter commented
> I was removing the deid scheme files from the branch, which are included from the very beginning of the branch.

You should not remove any files from the branch. When I created the branch used for this PR, the branch was a copy of the default branch of this repo (`develop`). Then we only need to add/update files needed to add the specification of the new COVID symptom annotation tool. When merging this PR, the changes that we made in this branch will be applied to the default branch. If you remove the file `openapi/commons/components/schemas/TextPersonNameAnnotation.yaml` as you did, this file would be removed from the default branch, which would break the specification of the Person Name Annotation tool. One of the reasons the checks are failing in this PR is because the series of tests I put in placed detect this break.

With `git revert 2561caaa27b5d151d8c22034e1413c5136894675`, you should be able to undo the commit `remove unrelated annotations` where you are remove files that we need to keep in this branch.

2021-04-27 04:39 UTC, yy6linda commented on openapi/commons/components/schemas/TextCovidSymptomAnnotation.yaml
> +  dateFormat: MM/DD/YYYY
need to have a new name other than the "dateFormat", maybe "symptom_type"?

2021-04-27 04:40 UTC, yy6linda commented on openapi/covid-symptom-annotator/components/schemas/TextCovidSymptomAnnotationRequest.yaml
> +description: A request to annotate COVID symptom in a clinical note
COVID symptoms

2021-04-27 07:37 UTC, cascadianblue requested changes

2021-04-27 07:37 UTC, cascadianblue commented on openapi/commons/components/schemas/TextCovidSymptomAnnotation.yaml
> +          Whether the annotation is positively or negatively corelated with the
`corelated` -> `correlated`

2021-04-27 07:37 UTC, cascadianblue commented on openapi/commons/components/schemas/TextCovidSymptomAnnotation.yaml
> +          Whether the annotation is positively or negatively corelated with the
Wouldn't this just be a function of `condition` (i.e. certain conditions are positively correlated with COVID-19, some are not)?

2021-04-27 07:37 UTC, cascadianblue commented on openapi/commons/components/schemas/TextCovidSymptomAnnotation.yaml
> +  dateFormat: MM/DD/YYYY
This line should be

```
condition: cough
```

2021-04-27 07:37 UTC, cascadianblue commented on openapi/covid-symptom-annotator/openapi.yaml
> +    The COVID Symptom Annotator is one of the first type of NLP Tools that can be
"one of the first types of NLP tools"

2021-04-27 07:37 UTC, cascadianblue commented on openapi/covid-symptom-annotator/openapi.yaml
> +    - [COVID Symptom Annotator Example (Python)](https://github.com/nlpsandbox/covid-symptom-annotator-example)
URL currently not reachable -- which might be intended

2021-04-27 15:35 UTC, tschaffter commented on openapi/covid-symptom-annotator/openapi.yaml
> +    The COVID Symptom Annotator is one of the first type of NLP Tools that can be
```suggestion
    The COVID Symptom Annotator is one of the first NLP Sandbox tools that can be
```

2021-04-27 15:36 UTC, tschaffter commented on openapi/covid-symptom-annotator/openapi.yaml
> +    The COVID Symptom Annotator is one of the first type of NLP Tools that can be
I now use the above suggestion in all other tool specifications.

2021-04-27 15:36 UTC, tschaffter commented on openapi/covid-symptom-annotator/openapi.yaml
> +    - [COVID Symptom Annotator Example (Python)](https://github.com/nlpsandbox/covid-symptom-annotator-example)
Yes, an example implementation will be added shortly and before the next release of the NLP Sandbox schemas.

2021-04-30 21:05 UTC, merged