id-annotator
nlpsandbox/nlpsandbox-schemas pull request #196
Opened 2021-04-16 23:31 UTC by yy6linda

Added an id-annotator data schema

2021-04-17 01:39 UTC, tschaffter requested changes
This PR looks great! Only one thing to address:

- Remove .DS_Store files

2021-04-19 17:19 UTC, cascadianblue requested changes

2021-04-19 17:19 UTC, cascadianblue commented on .github/workflows/ci.yml
> +        - "id-annotator"
it looks like the order of this list was alphabetical, though no big deal either way

2021-04-19 17:29 UTC, yy6linda commented on openapi/commons/components/schemas/TextIdAnnotation.yaml
> +          - vehicle
@cascadianblue Hi Connor, here the names are in the same convention as the i2b2 challenge. For the initial schema, we decided to keep it the same form as the challenge but we are open to changes later.

2021-04-19 17:34 UTC, yy6linda commented
@tschaffter changes made, please review.

2021-04-19 20:22 UTC, tschaffter commented on openapi/commons/components/schemas/TextIdAnnotation.yaml
> +          - vehicle
@yy6linda I agree with connor's suggestion. We should do this change now instead of waiting, which would lead tools to break.

2021-04-19 20:37 UTC, yy6linda commented on openapi/commons/components/schemas/TextIdAnnotation.yaml
> +          - vehicle
@tschaffter Sure, changes made, please let me know if it looks good now

2021-04-19 21:04 UTC, tschaffter commented on openapi/commons/components/schemas/TextIdAnnotation.yaml
> +          - vehicle
Looks great!

2021-04-19 21:06 UTC, tschaffter approved these changes
This PR looks good to me! 🚀

2021-04-19 21:07 UTC, tschaffter commented
@cascadianblue The PR looks good to me but would like a second PR approval to comply with a not yet documented SOP.

2021-04-20 15:23 UTC, tschaffter commented
## Update

Pending discussion and vote on whether the tool should be named Identifier Annotator or ID Annotator (poll on Discord).

2021-04-21 15:56 UTC, tschaffter commented
@cascadianblue I'm moving ahead and merging this PR to make it easier for Yao to start working on the example tool. I would still very like to get your review for the contact annotator (see #197 ). Thanks!

2021-04-21 15:58 UTC, tschaffter commented
Thanks @yy6linda for putting together this new tool specification! 🚀

2021-04-21 15:58 UTC, merged