add contact annotator schema
nlpsandbox/nlpsandbox-schemas pull request #197
Opened 2021-04-20 18:36 UTC by yy6linda

add contact annotator schema

2021-04-20 18:59 UTC, tschaffter requested changes

2021-04-20 18:59 UTC, tschaffter commented on openapi/commons/components/schemas/TextContactAnnotation.yaml
> +description: An contact annotation in a text
```suggestion
description: A contact annotation in a text
```

2021-04-20 18:59 UTC, tschaffter commented on openapi/commons/components/schemas/TextContactAnnotation.yaml
> +        enum:
Add the enum value "other" as we have in the physical address annotator

2021-04-20 18:59 UTC, tschaffter commented on openapi/contact-annotator/components/schemas/TextContactAnnotationResponse.yaml
> +description: The response to an contact annotation request
```suggestion
description: The response to a contact annotation request
```

2021-04-20 18:59 UTC, tschaffter commented on openapi/contact-annotator/openapi.yaml
> +    can be benchmarked on [nlpsandbox.io](https://nlpsandbox.io). An Contact Annotator takes as input a clinical note and outputs a list of
Limit lines to 80 characters. In VS Code, I use the plugin [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap). Once installed, just select the paragraph and press ALT + Q (on Windows).

2021-04-20 18:59 UTC, tschaffter commented on openapi/contact-annotator/paths/textContactAnnotations.yaml
> +  summary: Annotate Contacts in a clinical note
```suggestion
  summary: Annotate contacts in a clinical note
```

2021-04-20 18:59 UTC, tschaffter commented on openapi/contact-annotator/paths/textContactAnnotations.yaml
> +  description: Return the Contact annotations found in a clinical note
```suggestion
  description: Return the contact annotations found in a clinical note
```

2021-04-20 19:53 UTC, tschaffter approved these changes
This PR looks good! Thanks!

2021-04-23 15:13 UTC, tschaffter commented
@cascadianblue Thanks for reviewing this PR when you have a chance!

2021-04-27 07:47 UTC, cascadianblue commented on openapi/contact-annotator/openapi.yaml
> +    The Contact Annotator is one of the first type of NLP Tools that
"first types of"

2021-04-27 07:47 UTC, cascadianblue commented on openapi/contact-annotator/openapi.yaml
> +    The Contact Annotator is one of the first type of NLP Tools that
This is duplicate language as in #195 . I suppose they technically are both still "one of" the first, but at some point that makes less sense to say

2021-04-27 07:47 UTC, cascadianblue commented on openapi/contact-annotator/openapi.yaml
> +    provides a simple example implementation of a Python-Flask contact
It might be nice to call it a "rules-based" implementation. That is a common term in NLP

2021-04-27 07:47 UTC, cascadianblue commented on openapi/contact-annotator/openapi.yaml
> +      robustness, and security reasons. When benchmarked on [nlpsandbox.io](https://nlpsandbox.io),
Sentence would sound a bit clearer with flipped word order

> To ensure results are reproducible, robust, and secure, this tool cannot connect to any remote server.

2021-04-27 07:47 UTC, cascadianblue commented on openapi/contact-annotator/openapi.yaml
> +    - [Contact Annotator Example (Python)](https://github.com/nlpsandbox/contact-annotator-example)
Should this be commented out or marked TBA until it is made available?

2021-04-27 07:47 UTC, cascadianblue commented on openapi/contact-annotator/paths/textContactAnnotations.yaml
> +  summary: Annotate contacts in a clinical note
`contacts` -> `contact information`

2021-04-27 14:50 UTC, tschaffter commented on openapi/contact-annotator/openapi.yaml
> +    provides a simple example implementation of a Python-Flask contact
```suggestion
    provides a rules-based example implementation of a Python-Flask contact
```

2021-04-27 14:51 UTC, tschaffter commented on openapi/contact-annotator/openapi.yaml
> +      robustness, and security reasons. When benchmarked on [nlpsandbox.io](https://nlpsandbox.io),
```suggestion
    - To ensure results are reproducible, robust, and secure, this tool cannot connect to any remote server.
      When benchmarked on [nlpsandbox.io](https://nlpsandbox.io),
```

2021-04-27 14:53 UTC, tschaffter commented on openapi/contact-annotator/openapi.yaml
> +    - [Contact Annotator Example (Python)](https://github.com/nlpsandbox/contact-annotator-example)
This example will be created this week before creating a new release of the schema.

2021-04-27 14:55 UTC, tschaffter commented on openapi/contact-annotator/paths/textContactAnnotations.yaml
> +  summary: Annotate contacts in a clinical note
```suggestion
  summary: Annotate contact information in a clinical note
```

2021-04-27 14:57 UTC, tschaffter commented on openapi/contact-annotator/openapi.yaml
> +    The Contact Annotator is one of the first type of NLP Tools that
```suggestion
    The Contact Annotator is one of the first NLP Sandbox tools that
```

2021-04-27 14:58 UTC, tschaffter commented on openapi/contact-annotator/openapi.yaml
> +    The Contact Annotator is one of the first type of NLP Tools that
I will propagate this change to the other specifications.

2021-04-27 15:15 UTC, merged