Rewrap openapi description to 80-char lines
nlpsandbox/nlpsandbox-schemas pull request #200
Opened 2021-04-30 23:14 UTC by tschaffter

Prepare the NLP Sandbox schemas version 1.1.0.

### Notes

2021-05-07 01:55 UTC, ymnliu commented on README.md
> +These repositories provide example implementations of each NLP Sandbox tools.
"each NLP Sandbox ~~t~~Tool~~s~~"

2021-05-07 02:00 UTC, ymnliu commented on openapi/covid-symptom-annotator/openapi.yaml
> +    - To ensure results are reproducible, robust, and secure, this tool cannot
"To ensure _the_ results are reproducible"

2021-05-07 02:01 UTC, ymnliu commented on openapi/covid-symptom-annotator/openapi.yaml
> +    - To ensure results are reproducible, robust, and secure, this tool cannot
To ensure the data is secured, this tool cannot

2021-05-07 02:02 UTC, ymnliu commented on openapi/date-annotator/openapi.yaml
> +    A Date Annotator takes as input a clinical note and outputs a list of
A Date Annotator takes an input of clinical texts ...

2021-05-07 02:02 UTC, ymnliu commented on openapi/date-annotator/openapi.yaml
> +    predicted date annotations found in the clinical note. This OpenAPI document
clinical texts

2021-05-07 02:03 UTC, ymnliu commented on openapi/physical-address-annotator/openapi.yaml
> +    A Physical Address Annotator takes as input a clinical note and outputs a
an input of clinical texts

2021-05-07 20:16 UTC, cascadianblue requested changes

2021-05-07 20:16 UTC, cascadianblue commented on README.md
> +The OpenAPI specification - or schemas - of the NLP Sandbox tools listed below
"specification" should be "specifications"

2021-05-07 20:16 UTC, cascadianblue commented on openapi/commons/components/schemas/ToolDependencies.yaml
> +  tools:
I think I missed the process for deciding to change this property name. What is the rationale behind it?

2021-05-07 20:16 UTC, cascadianblue commented on openapi/contact-annotator/components/schemas/TextContactAnnotationRequest.yaml
> +      number is 203-333-4545.
Is this a real phone number? People usually start fake phone numbers with `555`s, e.g. `(203) 555-4545`

2021-05-07 20:16 UTC, cascadianblue commented on openapi/covid-symptom-annotator/openapi.yaml
> +    evaluate its performance on [nlpsandbox.io](https://nlpsandbox.io).
"Your NLP Sandbox tool must meet the following conditions before evaluating its performance on [nlpsandbox.io](...):"

2021-05-11 15:01 UTC, tschaffter commented on README.md
> +These repositories provide example implementations of each NLP Sandbox tools.
Is the comment about the incorrect plural form? This typo will be fixed in my next commit.

2021-05-11 15:04 UTC, ymnliu commented on README.md
> +These repositories provide example implementations of each NLP Sandbox tools.
@tschaffter yes it is about that.

2021-05-11 15:05 UTC, tschaffter commented on openapi/covid-symptom-annotator/openapi.yaml
> +    - To ensure results are reproducible, robust, and secure, this tool cannot
This item will become:

    - To ensure the results are reproducible and robust, and the data are
      secured, this tool must not connect to any remote server. When benchmarked
      on [nlpsandbox.io](https://nlpsandbox.io), this tool will not be able to
      connect to remote servers.

2021-05-11 15:12 UTC, tschaffter commented on openapi/date-annotator/openapi.yaml
> +    predicted date annotations found in the clinical note. This OpenAPI document
same comment as above

2021-05-11 15:13 UTC, tschaffter commented on openapi/covid-symptom-annotator/components/schemas/TextCovidSymptomAnnotationRequest.yaml
> +      dry cough for almost a week now.
Fixed in next commit

2021-05-11 15:16 UTC, tschaffter commented on openapi/commons/components/schemas/ToolDependencies.yaml
> +  tools:
The motivation is that it's clear from the schema name (`ToolDependencies.yaml`) that this object is about the dependencies of the tool. There should not be a need to repeat the "Dependencies" part in the property name. Moreover, the items listed in the array now called `tools` are `Tool` objects.

2021-05-11 15:17 UTC, tschaffter commented on openapi/contact-annotator/components/schemas/TextContactAnnotationRequest.yaml
> +      number is 203-333-4545.
Replaced phone number to 203-555-4545. Kept current format to now have to update code.

2021-05-11 15:26 UTC, merged